<?php

namespace Enchere\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConteneurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConteneurRepository extends EntityRepository
{
}
