users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /


