main_homepage:
    path: /
    defaults: { _controller: MainBundle:Default:index }
enchere_page:
    path: /enchere
    defaults: { _controller: MainBundle:Default:enchere }
top_page:
    path: /classement
    defaults: {_controller: MainBundle:Default:top}
apropos_page:
    path: /apropos
    defaults: {_controller: MainBundle:Default:apropos}
